import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Button } from "@/components/ui/button";
import { ClerkProvider, UserButton } from "@clerk/nextjs";

const notoSans = Noto_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "W ePlus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={notoSans.variable} suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            defaultTheme="system"
            storageKey="make-it-smooth-theme"
          >
            <div className="flex justify-between">
              <div className="flex justify-start mb-4 p-5 font-bold text-4xl">
                <p>We+</p>
              </div>
              <div className="flex mb-4 p-5 gap-4">
                <Button variant={'link'} className="px-0 cursor-pointer">Chat</Button>
                <Button variant={'link'} className="px-0 cursor-pointer">Files</Button>
                <Button variant={'link'} className="px-0 cursor-pointer">Agents</Button>
                <ThemeToggle />
                <UserButton />
              </div>
            </div>

            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
